# Activar I2C para el MCP23017
CONFIG_I2C=y
CONFIG_GPIO_MCP23017=y

# Necesario para que el expansor funcione con la matriz
CONFIG_ZMK_KSCAN_MATRIX_WAIT_BEFORE_INPUTS=100
CONFIG_ZMK_KSCAN_MATRIX_WAIT_AFTER_INPUTS=100

# Activar Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Opcional: Soporte para más de 5 capas si es necesario
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Aumentar la potencia del Bluetooth (recomendado para teclados con carcasas metálicas o muchos componentes)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Activar Deep Sleep para ahorrar batería (entra en sueño tras 15 min de inactividad)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000