# Activar I2C para el MCP23017
CONFIG_I2C=y
CONFIG_GPIO_MCP23017=y

# Activar Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Opcional: Soporte para más de 5 capas si es necesario
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5